version: '3.3'

services:
  db:
    image: mariadb
    container_name: lfp_docker_mariadb
    restart: always
    volumes:
      - lfp-db-data:/var/lib/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - dev
    ports:
      - "33006:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lfp_docker_rabbitmq
    volumes:
      - rmqconf:/etc/rabbitmq
      - rmqdata:/var/lib/rabbitmq/mnesia
      - rmqlogs:/var/log/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${CUSTOM_RABBIT_MANAGER_PORT}:15672"
      - "${CUSTOM_RABBIT_PORT}:5672"
    env_file:
      - .env

  php-fpm:
    container_name: lfp_php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db
      - rabbitmq
    networks:
      - dev
    volumes:
      - ./:/var/www/
    environment:
      UPLOAD_LIMIT: 64M

  nginx:
    container_name: lfp_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
    depends_on:
      - db
      - php-fpm
    networks:
      - dev
    ports:
      - "8080:80"

networks:
  dev:

volumes:
  lfp-db-data:
  rmqconf:
    driver: local
  rmqlogs:
    driver: local
  rmqdata:
    driver: local
